version: "3.8"

services:
  web:
    env_file: "app.env"
    container_name: researchcruiseapp-frontend-dc
    build:
      context: ./frontend
      target: production
    volumes:
      - ./frontend:/researchcruiseapp-frontend-dc
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  api:
    env_file: "app.env"
    build:
      context: ./ResearchCruiseApp-API/
    container_name: researchcruiseapp-api-dc
    environment:
      - APP_UID=1000
    ports:
      - "8080:8080"
    restart: always
